"""
Generate a small synthetic SITELLE data cube in the legacy (quadrant) HDF5 format
that LUCI reads.

This exists so the test suite does not depend on a multi-gigabyte observation
sitting at a hardcoded path on one person's laptop.  The cube is small enough to
build in a fixture (a few MB), and every emission line in it is injected at a
*known* velocity and broadening, so tests can assert on recovered physics rather
than merely "the code ran".

The emission-line model here is written out longhand from the sinc-Gauss
definition rather than imported from ``LUCI.LuciFunctions``.  That is deliberate:
if the fixture were generated by the same code under test, a "we recover the
input velocity" assertion would be circular.

Layout written (matching what ``LuciUtility.update_header`` and
``LuciBase.Luci.read_in_cube`` expect):

    /                      attrs: quad_nb, dimx, dimy, dimz
    /header                compound array, rows of (name, value, comment, dtype)
    /calib_map             (dimx, dimy) calibration-laser wavelength map
    /quad000 .. /quad00N   groups, each with a 'data' dataset
    /deep_frame            optional (dimx, dimy)

Usage::

    python tests/fixtures/make_cube.py --out /tmp/luci_fixture --filter SN3
    # writes /tmp/luci_fixture.hdf5  (LUCI appends the extension itself)
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field

import h5py
import numpy as np
from scipy import special as sps

SPEED_OF_LIGHT = 299792.0  # km/s
FWHM_SINC_COEFF = 1.20671

# Rest wavelengths in nm, matching Fit.line_dict.
LINE_WAVELENGTHS = {
    "Halpha": 656.280,
    "NII6583": 658.341,
    "NII6548": 654.803,
    "SII6716": 671.647,
    "SII6731": 673.085,
    "OIII5007": 500.684,
    "OIII4959": 495.891,
    "Hbeta": 486.133,
    "OII3726": 372.603,
    "OII3729": 372.882,
}


@dataclass(frozen=True)
class FilterProfile:
    """
    Per-filter cube geometry.

    ``axis_min``/``axis_max`` are chosen so the synthetic spectral axis spans
    every window the current code looks at for this filter: the fit window
    (``LuciFit.restrict_wavelength``), the noise window
    (``LuciFit.calculate_noise``, which for SN2/SN3 sits *outside* the fit
    window), and the reference-spectrum clip
    (``LuciUtility.read_in_reference_spectrum``).  Getting this wrong produces
    an empty noise slice and a silent NaN, so the bounds are asserted in
    ``validate()`` below rather than left to trust.
    """

    name: str
    step_nb: int
    zpd_index: int
    axis_min: float  # cm^-1
    axis_max: float  # cm^-1
    fit_window: tuple[float, float]
    noise_window: tuple[float, float]
    reference_window: tuple[float, float]
    default_lines: tuple[str, ...]
    amplitude_ratios: dict[str, float] = field(default_factory=dict)

    @property
    def cdelt3(self) -> float:
        return (self.axis_max - self.axis_min) / self.step_nb

    @property
    def step(self) -> float:
        """Optical path step in nm, back-solved so sinc_width == cdelt3."""
        return 1e7 / (2.0 * self.cdelt3 * (self.step_nb - self.zpd_index))

    def validate(self) -> None:
        lo, hi = self.axis_min, self.axis_max
        for label, (wlo, whi) in (
            ("fit", self.fit_window),
            ("noise", self.noise_window),
            ("reference", self.reference_window),
        ):
            if not (lo <= wlo and whi <= hi):
                raise ValueError(
                    f"{self.name}: {label} window {(wlo, whi)} is not contained in the spectral axis {(lo, hi)}"
                )


PROFILES: dict[str, FilterProfile] = {
    "SN3": FilterProfile(
        name="SN3",
        step_nb=842,
        zpd_index=169,
        axis_min=14400.0,
        axis_max=16100.0,
        fit_window=(14750.0, 15400.0),
        noise_window=(15600.0, 15800.0),
        reference_window=(14700.0, 15600.0),
        default_lines=("Halpha", "NII6548", "NII6583", "SII6716", "SII6731"),
        amplitude_ratios={
            "Halpha": 1.0,
            "NII6583": 0.40,
            "NII6548": 0.133,  # locked to NII6583/3 by the NII_constraints() path
            "SII6716": 0.30,
            "SII6731": 0.21,
        },
    ),
    "SN2": FilterProfile(
        name="SN2",
        step_nb=842,
        zpd_index=169,
        axis_min=18400.0,
        axis_max=21200.0,
        fit_window=(19500.0, 20750.0),
        noise_window=(18600.0, 19000.0),
        reference_window=(19000.0, 21000.0),
        default_lines=("Hbeta", "OIII4959", "OIII5007"),
        amplitude_ratios={"Hbeta": 0.35, "OIII4959": 0.33, "OIII5007": 1.0},
    ),
    "SN1": FilterProfile(
        name="SN1",
        step_nb=842,
        zpd_index=169,
        axis_min=25400.0,
        axis_max=28200.0,
        fit_window=(26000.0, 28000.0),
        noise_window=(26000.0, 26200.0),
        reference_window=(25500.0, 27500.0),
        default_lines=("OII3726", "OII3729"),
        amplitude_ratios={"OII3726": 1.0, "OII3729": 0.75},
    ),
}


def line_position(line: str, velocity_kms: float) -> float:
    """Observed line position in cm^-1 for a given velocity."""
    lam = LINE_WAVELENGTHS[line]
    return 1e7 / (lam * (1.0 + velocity_kms / SPEED_OF_LIGHT))


def line_sigma(line: str, velocity_kms: float, broadening_kms: float) -> float:
    """Gaussian sigma in cm^-1 for a given broadening."""
    return line_position(line, velocity_kms) * broadening_kms / SPEED_OF_LIGHT


def sincgauss(axis: np.ndarray, amplitude: float, position: float, sigma: float, sinc_width: float) -> np.ndarray:
    """
    Sinc convolved with a Gaussian, in the Dawson-function form used for SITELLE.

    Written independently of ``LUCI.LuciFunctions.SincGauss`` on purpose -- see
    the module docstring.
    """
    width = sinc_width / (np.pi * FWHM_SINC_COEFF)
    a = np.float64(sigma / (np.sqrt(2.0) * width))
    b = ((axis - position) / (np.sqrt(2.0) * sigma)).astype(np.float64)
    d1 = sps.dawsn(1j * a + b) * np.exp(2.0 * 1j * a * b)
    d2 = sps.dawsn(1j * a - b) * np.exp(-2.0 * 1j * a * b)
    d3 = 2.0 * sps.dawsn(1j * a)
    return np.real(amplitude * (d1 + d2) / d3)


def gaussian(axis: np.ndarray, amplitude: float, position: float, sigma: float) -> np.ndarray:
    return amplitude * np.exp(-0.5 * ((axis - position) / sigma) ** 2)


def sinc(axis: np.ndarray, amplitude: float, position: float, sinc_width: float) -> np.ndarray:
    return amplitude * np.sinc((axis - position) / sinc_width)


def make_spectrum(
    axis: np.ndarray,
    profile: FilterProfile,
    lines: tuple[str, ...],
    velocity_kms: float,
    broadening_kms: float,
    amplitude: float,
    continuum: float,
    sinc_width: float,
    model: str = "sincgauss",
    noise_sigma: float = 0.0,
    rng: np.random.Generator | None = None,
    absorption_depth: float = 0.0,
    absorption_broadening_kms: float = 200.0,
    absorption_line: str = "Halpha",
) -> np.ndarray:
    """
    Build a single synthetic spectrum with known line parameters.

    With ``absorption_depth`` > 0 a stellar absorption trough is added under
    ``absorption_line``: a Gaussian eating that fraction of the continuum at its
    centre, broad (``absorption_broadening_kms``) compared with the emission. It
    shares the emission's velocity, which is the hard case -- a trough offset from
    the line would be separable by position alone.
    """
    spectrum = np.full_like(axis, continuum, dtype=np.float64)
    if absorption_depth:
        pos = line_position(absorption_line, velocity_kms)
        sigma = pos * absorption_broadening_kms / SPEED_OF_LIGHT
        spectrum -= absorption_depth * continuum * np.exp(-0.5 * ((axis - pos) / sigma) ** 2)
    for line in lines:
        amp = amplitude * profile.amplitude_ratios.get(line, 1.0)
        pos = line_position(line, velocity_kms)
        sig = line_sigma(line, velocity_kms, broadening_kms)
        if model == "sincgauss":
            spectrum += sincgauss(axis, amp, pos, sig, sinc_width)
        elif model == "gaussian":
            spectrum += gaussian(axis, amp, pos, sig)
        elif model == "sinc":
            spectrum += sinc(axis, amp, pos, sinc_width)
        else:
            raise ValueError(f"unknown model {model!r}")
    if noise_sigma > 0.0:
        rng = rng or np.random.default_rng(0)
        spectrum += rng.normal(0.0, noise_sigma, size=axis.shape)
    return spectrum


def _quadrant_bounds(quad_number: int, quad_nb: int, dimx: int, dimy: int):
    """
    Mirror of ``LuciUtility.get_quadrant_dims`` so the file we write is sliced
    exactly the way the reader will slice it back.
    """
    div_nb = int(np.sqrt(quad_nb))
    index_x = quad_number % div_nb
    index_y = (quad_number - index_x) // div_nb
    x_min = int(index_x * np.floor(dimx / div_nb))
    x_max = int((index_x + 1) * np.floor(dimx / div_nb)) if index_x != div_nb - 1 else dimx
    y_min = int(index_y * np.floor(dimy / div_nb))
    y_max = int((index_y + 1) * np.floor(dimy / div_nb)) if index_y != div_nb - 1 else dimy
    return x_min, x_max, y_min, y_max


def _header_rows(
    profile: FilterProfile, dimx: int, dimy: int, calib_nm: float
) -> list[tuple[bytes, bytes, bytes, bytes]]:
    """
    Rows for the /header compound dataset.

    ``update_header`` reads field 0 as the key, field 1 as the value and field 3
    as the dtype string, and cleans them with a ``str(...).replace()`` chain that
    strips every lowercase 'b'.  Keys and values must therefore avoid lowercase
    'b' -- all-uppercase FITS keywords are safe.

    PC matrix elements are supplied explicitly and deliberately non-identity:
    ``create_deep_image(binning=...)`` indexes ``header['PC1_1']`` directly, and
    astropy omits the PC matrix from ``WCS.to_header()`` when it is the identity,
    which would raise KeyError.
    """
    values: list[tuple[str, object, str]] = [
        ("SIMPLE", "T", "bool"),
        ("NAXIS", 3, "int64"),
        ("NAXIS1", dimx, "int64"),
        ("NAXIS2", dimy, "int64"),
        ("NAXIS3", profile.step_nb, "int64"),
        ("CTYPE1", "RA---TAN", "str"),
        ("CTYPE2", "DEC--TAN", "str"),
        ("CRVAL1", 24.174, "float64"),
        ("CRVAL2", 15.783, "float64"),
        ("CRPIX1", dimx / 2.0, "float64"),
        ("CRPIX2", dimy / 2.0, "float64"),
        ("CDELT1", -8.1e-05, "float64"),
        ("CDELT2", 8.1e-05, "float64"),
        ("CUNIT1", "deg", "str"),
        ("CUNIT2", "deg", "str"),
        ("PC1_1", 0.9998, "float64"),
        ("PC1_2", -0.0199, "float64"),
        ("PC2_1", 0.0199, "float64"),
        ("PC2_2", 0.9998, "float64"),
        ("CRVAL3", profile.axis_min, "float64"),
        ("CDELT3", profile.cdelt3, "float64"),
        ("STEP", profile.step, "float64"),
        ("STEPNB", profile.step_nb, "int64"),
        ("ZPDINDEX", profile.zpd_index, "int64"),
        ("ORDER", 8, "int64"),
        ("FILTER", profile.name, "str"),
        ("CALIBNM", calib_nm, "float64"),
        ("DATE-OBS", "2019-10-01", "str"),
        ("EXPTIME", 13.3, "float64"),
        ("OSJT", "TEST", "str"),
    ]
    rows = []
    for key, value, dtype in values:
        rows.append(
            (
                key.encode("ascii"),
                str(value).encode("ascii"),
                b"",
                dtype.encode("ascii"),
            )
        )
    return rows


def write_cube(
    path: str,
    filter_name: str = "SN3",
    dimx: int = 20,
    dimy: int = 20,
    quad_nb: int = 4,
    velocity_kms: float = 100.0,
    broadening_kms: float = 30.0,
    amplitude: float = 1.0e-16,
    continuum: float = 1.0e-17,
    model: str = "sincgauss",
    noise_sigma: float = 1.0e-18,
    calib_nm: float = 543.5,
    max_theta_deg: float = 12.0,
    include_deep_frame: bool = False,
    seed: int = 20240101,
    absorption_depth: float = 0.0,
    absorption_broadening_kms: float = 200.0,
) -> dict:
    """
    Write a synthetic cube and return the ground truth used to build it.

    Notes on the chosen defaults:

    * ``amplitude``/``continuum`` are ~1e-16 because ``read_in_cube`` silently
      replaces any value above 1e-9 or below -1e-16 with 1e-22.  Unit-scale
      fluxes would be zeroed out on read and every fit would return garbage.
    * ``dimx``/``dimy`` default to a multiple of 10 because ``create_deep_image``
      sums the cube in exactly ten slabs of ``int(shape[0] / 10)`` rows and
      silently drops the remainder.
    * ``quad_nb`` must be a perfect square; ``get_quadrant_dims`` takes its
      square root.
    """
    if int(np.sqrt(quad_nb)) ** 2 != quad_nb:
        raise ValueError(f"quad_nb must be a perfect square, got {quad_nb}")

    profile = PROFILES[filter_name]
    profile.validate()

    if not path.endswith(".hdf5"):
        path = path + ".hdf5"

    rng = np.random.default_rng(seed)
    axis = np.linspace(
        profile.axis_min,
        profile.axis_min + profile.step_nb * profile.cdelt3,
        profile.step_nb,
    )
    lines = profile.default_lines

    # Interferometer angle grows radially from the optical axis, as on the real
    # instrument.  calib_map = calib_ref / cos(theta) inverts the relation in
    # LuciUtility.get_interferometer_angles.
    yy, xx = np.meshgrid(np.arange(dimy), np.arange(dimx))
    radius = np.hypot(xx - dimx / 2.0, yy - dimy / 2.0)
    theta = np.deg2rad(max_theta_deg * radius / max(radius.max(), 1.0))
    calib_map = calib_nm / np.cos(theta)

    # One spectrum per pixel; sinc width follows the local interferometer angle
    # exactly as Fit.calc_sinc_width() will recompute it.
    cube = np.empty((dimx, dimy, profile.step_nb), dtype=np.float64)
    for i in range(dimx):
        for j in range(dimy):
            cos_theta = np.cos(theta[i, j])
            mpd = cos_theta * profile.step * (profile.step_nb - profile.zpd_index) / 1e7
            sinc_width = 1.0 / (2.0 * mpd)
            cube[i, j, :] = make_spectrum(
                axis,
                profile,
                lines,
                velocity_kms,
                broadening_kms,
                amplitude,
                continuum,
                sinc_width,
                model=model,
                noise_sigma=noise_sigma,
                rng=rng,
                absorption_depth=absorption_depth,
                absorption_broadening_kms=absorption_broadening_kms,
            )

    with h5py.File(path, "w") as f:
        f.attrs["quad_nb"] = quad_nb
        f.attrs["dimx"] = dimx
        f.attrs["dimy"] = dimy
        f.attrs["dimz"] = profile.step_nb

        rows = _header_rows(profile, dimx, dimy, calib_nm)
        dt = np.dtype([("a", "S64"), ("b", "S64"), ("c", "S64"), ("d", "S16")])
        f.create_dataset("header", data=np.array(rows, dtype=dt))

        f.create_dataset("calib_map", data=calib_map.astype(np.float64))

        for iquad in range(quad_nb):
            x0, x1, y0, y1 = _quadrant_bounds(iquad, quad_nb, dimx, dimy)
            grp = f.create_group("quad00%i" % iquad)
            grp.create_dataset("data", data=cube[x0:x1, y0:y1, :])

        if include_deep_frame:
            f.create_dataset("deep_frame", data=np.nansum(cube, axis=2) / profile.step_nb)

    return {
        "path": path,
        "filter": filter_name,
        "dimx": dimx,
        "dimy": dimy,
        "dimz": profile.step_nb,
        "quad_nb": quad_nb,
        "lines": list(lines),
        "velocity_kms": velocity_kms,
        "broadening_kms": broadening_kms,
        "amplitude": amplitude,
        "continuum": continuum,
        "model": model,
        "noise_sigma": noise_sigma,
        "absorption_depth": absorption_depth,
        "absorption_broadening_kms": absorption_broadening_kms,
        "axis_min": profile.axis_min,
        "axis_max": profile.axis_min + profile.step_nb * profile.cdelt3,
        "cdelt3": profile.cdelt3,
        "step": profile.step,
        "step_nb": profile.step_nb,
        "zpd_index": profile.zpd_index,
        "calib_nm": calib_nm,
    }


def write_new_format_cube(
    path: str, filter_name: str = "SN3", dimx: int = 20, dimy: int = 20, calib_nm: float = 543.5
) -> dict:
    """
    Write a cube in the *new* SITELLE HDF5 layout.

    The two formats differ structurally, and ``read_in_cube`` / ``update_header``
    branch on the presence of a ``quad_nb`` attribute:

      * **legacy** -- header in a ``/header`` compound dataset, data split across
        ``/quad00N/data`` groups (what :func:`write_cube` produces);
      * **new** -- header keys as HDF5 *attributes* on the root group, data in a
        single ``/data`` dataset.

    The new-format path had no test coverage, which is how B15 survived: it type
    checked with ``header_type is np.str``, removed in numpy 1.24, and the
    resulting ``AttributeError`` was swallowed by a bare ``except`` -- leaving the
    WCS dictionary empty and producing a cube with no axes.

    Kept deliberately small: this exists to exercise the header/type branch, not
    to fit anything.
    """
    profile = PROFILES[filter_name]
    if not path.endswith(".hdf5"):
        path = path + ".hdf5"

    axis = np.linspace(profile.axis_min, profile.axis_min + profile.step_nb * profile.cdelt3, profile.step_nb)
    rng = np.random.default_rng(7)
    cube = np.empty((dimx, dimy, profile.step_nb), dtype=np.float64)
    sinc_width = profile.cdelt3
    for i in range(dimx):
        for j in range(dimy):
            cube[i, j, :] = make_spectrum(
                axis,
                profile,
                profile.default_lines,
                100.0,
                30.0,
                1.0e-16,
                1.0e-17,
                sinc_width,
                noise_sigma=1.0e-18,
                rng=rng,
            )

    yy, xx = np.meshgrid(np.arange(dimy), np.arange(dimx))
    radius = np.hypot(xx - dimx / 2.0, yy - dimy / 2.0)
    theta = np.deg2rad(12.0 * radius / max(radius.max(), 1.0))

    # Deliberately mixed dtypes, since the type dispatch is what is under test:
    # floats, ints, strings and a bool must each land in the right branch.  Strings
    # are plain `str` because h5py cannot store numpy unicode ('<U8') attributes --
    # which is also what real ORBS-written cubes contain.
    attrs: dict[str, object] = {
        "NAXIS": np.int64(3),
        "NAXIS1": np.int64(dimx),
        "NAXIS2": np.int64(dimy),
        "NAXIS3": np.int64(profile.step_nb),
        "CTYPE1": "RA---TAN",
        "CTYPE2": "DEC--TAN",
        "CRVAL1": np.float64(24.174),
        "CRVAL2": np.float64(15.783),
        "CRPIX1": np.float64(dimx / 2.0),
        "CRPIX2": np.float64(dimy / 2.0),
        "CDELT1": np.float64(-8.1e-05),
        "CDELT2": np.float64(8.1e-05),
        "CUNIT1": "deg",
        "CUNIT2": "deg",
        "PC1_1": np.float64(0.9998),
        "PC1_2": np.float64(-0.0199),
        "PC2_1": np.float64(0.0199),
        "PC2_2": np.float64(0.9998),
        "CRVAL3": np.float64(profile.axis_min),
        "CDELT3": np.float64(profile.cdelt3),
        "STEP": np.float64(profile.step),
        "STEPNB": np.int64(profile.step_nb),
        "ZPDINDEX": np.int64(profile.zpd_index),
        "ORDER": np.int64(8),
        "FILTER": filter_name,
        "CALIBNM": np.float64(calib_nm),
        "DATE-OBS": "2019-10-01",
        "EXPTIME": np.float64(13.3),
        "WAVTYPE": "WAVENUMBER",
        "APODIZE": np.bool_(False),
    }

    with h5py.File(path, "w") as f:
        for key, value in attrs.items():
            f.attrs[key] = value
        f.create_dataset("data", data=cube)
        f.create_dataset("calib_map", data=(calib_nm / np.cos(theta)).astype(np.float64))

    return {
        "path": path,
        "filter": filter_name,
        "dimx": dimx,
        "dimy": dimy,
        "dimz": profile.step_nb,
        "velocity_kms": 100.0,
        "broadening_kms": 30.0,
        "step_nb": profile.step_nb,
        "zpd_index": profile.zpd_index,
        "axis_min": profile.axis_min,
        "attrs": attrs,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, help="output path (.hdf5 appended if absent)")
    parser.add_argument("--filter", default="SN3", choices=sorted(PROFILES))
    parser.add_argument("--dimx", type=int, default=20)
    parser.add_argument("--dimy", type=int, default=20)
    parser.add_argument("--quad-nb", type=int, default=4)
    parser.add_argument("--velocity", type=float, default=100.0)
    parser.add_argument("--broadening", type=float, default=30.0)
    parser.add_argument("--model", default="sincgauss", choices=("sincgauss", "gaussian", "sinc"))
    parser.add_argument("--noise", type=float, default=1.0e-18)
    parser.add_argument("--deep-frame", action="store_true")
    args = parser.parse_args()

    truth = write_cube(
        args.out,
        filter_name=args.filter,
        dimx=args.dimx,
        dimy=args.dimy,
        quad_nb=args.quad_nb,
        velocity_kms=args.velocity,
        broadening_kms=args.broadening,
        model=args.model,
        noise_sigma=args.noise,
        include_deep_frame=args.deep_frame,
    )
    for key, value in truth.items():
        print(f"{key:>14}: {value}")


if __name__ == "__main__":
    main()
